#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit on command errors and treat unset variables as an error
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)
db_pwd=$(ynh_app_setting_get "$app" mysqlpwd)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP OF THE MAIN DIR OF THE APP
#=================================================

ynh_backup "$final_path" "sources"

#=================================================
# BACKUP OF THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"

#=================================================
# BACKUP OF THE PHP-FPM CONFIGURATION
#=================================================

ynh_backup "/etc/php5/fpm/pool.d/$app.conf" "php-fpm.conf"
ynh_backup "/etc/php5/fpm/conf.d/20-$app.ini" "php-fpm.ini"

#=================================================
# BACKUP OF THE SQL BDD
#=================================================

mysqldump -u "$db_name" -p"$db_pwd" --no-create-db "$db_name" > ./db.sql

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP OF THE CRON FILE
#=================================================
ynh_backup "/etc/cron.d/$app" "cron"
