#!/bin/bash

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
YNH_VERSION	# Récupère le numéro de version de Yunohost.
if [ $ynh_version = "2.4" ]; then
	app=$YNH_APP_INSTANCE_NAME

	# Source app helpers
	source /usr/share/yunohost/helpers
else
	app=leed
	MYSQL_ROOT_PWD_FILE="/etc/yunohost/mysql"
fi
domain=$(sudo yunohost app setting $app domain)

REMOVE_BDD $app	# Suppression de la base de donnée et de l'utilisateur associé.

SECURE_REMOVE '/var/www/$app'	# Suppression du dossier de l'application

REMOVE_NGINX_CONF	# Suppression de la configuration nginx

REMOVE_FPM_CONF	# Suppression de la configuration du pool php-fpm

# Retirer le cron
if [ -e "/etc/cron.d/$app" ]; then
	echo "Delete cron"
	sudo rm "/etc/cron.d/$app"
fi

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color
