#!/bin/bash

db_user=leed
db_name=leed
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting leed domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/leed
sudo rm -f /etc/nginx/conf.d/$domain.d/leed.conf