#!/bin/bash

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
YNH_VERSION	# Récupère le numéro de version de Yunohost.
if [ "$version" = "2.4" ]; then
	app=$YNH_APP_INSTANCE_NAME
else
	app=leed
fi
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
admin=$(sudo yunohost app setting $app admin)
is_public=$(sudo yunohost app setting $app is_public)
final_path=$(sudo yunohost app setting $app final_path)
db_pwd=$(sudo yunohost app setting $app mysqlpwd)


CHECK_PATH	# Vérifie et corrige la syntaxe du path.

SETUP_SOURCE "leed.tar.gz"	# Télécharge la source, décompresse et copie dans $final_path

# Et copie le fichier de config nginx
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Set right permissions
sudo chown -R www-data: $final_path

# Change variables in Leed configuration
sudo sed -i "s@__PATH__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/$app.conf

# Créer le fichier de configuration du pool php-fpm et le configure.
sed -i "s@__NAMETOCHANGE__@$app@g" ../conf/php-fpm.conf
sed -i "s@__FINALPATH__@$final_path@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/$app.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
finalphpini=/etc/php5/fpm/conf.d/20-$app.ini
sudo cp ../conf/php-fpm.ini $finalphpini
sudo chown root: $finalphpini
sudo service php5-fpm reload

# Configure les droits d'accès au fichiers
# -rw-r--r-- sur les fichiers
sudo find $final_path -type f | xargs sudo chmod 644
# drwxr-xr-x sur les dossiers
sudo find $final_path -type d | xargs sudo chmod 755
# Les fichiers appartiennent à root
sudo chown -R root: $final_path

# www-data doit avoir les droits d'écriture dans plugins, cache et updates
sudo mkdir -p $final_path/cache
sudo chown -R www-data $final_path/cache $final_path/plugins $final_path/updates


# Récupération du code de synchronisation
db_user=$app
code_sync=$(mysql -h localhost -u $db_user -p$db_pwd -s $db_user -e 'SELECT value FROM leed_configuration WHERE `key`="synchronisationCode"' | sed -n 1p)

# Mise en place du cron pour la synchronisation
sed -i "s@__ADMIN__@$admin@g" ../conf/cron_leed
sed -i "s@__DOMAIN__@$domain@g" ../conf/cron_leed
sed -i "s@__PATH__@$path@g" ../conf/cron_leed
sed -i "s@__CODESYNC__@$code_sync@g" ../conf/cron_leed
sudo cp ../conf/cron_leed /etc/cron.d/$app

# Laisse un accès libre pour curl.
sudo yunohost app setting $app unprotected_uris -v "/"
# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf
# Lance la procédure de mise à jour de leed.
curl -kL https://$domain$path

# Make app private if necessary
sudo yunohost app setting $app is_public -v "$is_public"
if [ "$is_public" = "No" ];
then
	# Retire l'autorisation d'accès à leed
	sudo yunohost app setting $app unprotected_uris -d
	# Rend la page d'actualisation accessible pour le script cron.
	sudo yunohost app setting $app skipped_uris -v "/action.php"
fi

# Recharge la configuration Nginx
sudo service nginx reload
# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf


# Le thème par défaut présente actuellement un bug sur la langue et l'affichage du texte.
mysql -h localhost -u $db_user -p$db_pwd -s $db_user -e 'UPDATE leed_configuration SET `value`="marigolds-old" WHERE `key`="theme"'	# On force l'ancien thème
